nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "8282:8282"
node1:
    build: ./server
    links:
        - redis
    ports:
        - "8181"
node2:
    build: ./server
    links:
        - redis
    ports:
        - "8181"
node3:
    build: ./server
    links:
        - redis
    ports:
        - "8181"
redis:
    image: redis
    ports:
        - "6379"

