# Set nginx base image
FROM nginx

# File Author / Maintainer
MAINTAINER Aaron Schuenemann
EXPOSE 8282


# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx.conf

